### PR TITLE
two notebooks to illustrate some features of resampling

### PR DESCRIPTION
**Pull request by HDembinski**
This adds two very simple Jupyter notebooks that demonstrate some facilities of the library.

### CODE REVIEW

**Comment by dsaxton** [comment]
> This adds two very simple Jupyter notebooks that demonstrate some facilities of the library.

@HDembinski How do you feel about checking in code-only notebooks? That way the diff is minimized if / when someone makes changes. Or do you think it's best to do a clean run so that some useful output is already there?

**Comment by dsaxton** [comment]
Taking a quick glance at them, if we're to use them for communicating features it might be helpful to break them up into multiple cells and include markdown descriptions between so that they read more like prose

**Comment by HDembinski** [comment]
> Taking a quick glance at them, if we're to use them for communicating features it might be helpful to break them up into multiple cells and include markdown descriptions between so that they read more like prose

Feel free to improve them as you see fit. I didn't spend a lot of time writing them, consider these as stubs.

**Comment by HDembinski** [comment]
> > This adds two very simple Jupyter notebooks that demonstrate some facilities of the library.
> 
> @HDembinski How do you feel about checking in code-only notebooks? That way the diff is minimized if / when someone makes changes. Or do you think it's best to do a clean run so that some useful output is already there?

I am not sure what you mean, so I apologize in advance if I am not answering on piont. The notebooks should serve as little tutorials on specific topics, they are supposed to be educational and to advertise the library. So they should not only contain code, but also prose. Diffing them is difficult, as is diffing documentation in general.

**Comment by HDembinski** [comment]
We need to add some unit tests for the notebook, to make sure they continue to work as we make changes.

I use this script in iminuit to test my notebooks. These not tests for correctness of the output (which is guaranteed by the actual unit tests), but tests that change in the interface did not accidentally break the notebooks.
https://github.com/scikit-hep/iminuit/blob/develop/tutorial/test_notebooks.py

**Comment by dsaxton** [comment]
> I am not sure what you mean, so I apologize in advance if I am not answering on piont. The notebooks should serve as little tutorials on specific topics, they are supposed to be educational and to show-case the library. So they should not only contain code, but also prose. Diffing them is difficult, as is diffing documentation in general.

I suppose instead of "code-only" I more meant "no output" (so restarting a clearing cells before committing). That way we're only version controlling code and markdown content (and not metadata associated with a notebook run).

**Comment by HDembinski** [comment]
The idea is to have the notebooks in the repo so that people can look at them and the cell output.

**Comment by dsaxton** [comment]
> The idea is to have the notebooks in the repo so that people can look at them and the cell output.

Yeah, having them be viewable from the GitHub UI seems more important

**Comment by HDembinski** [comment]
@dsaxton Can this be merged now? We can always improve the notebooks later.

**Comment by dsaxton** [comment]
> @dsaxton Can this be merged now? We can always improve the notebooks later.

My preference would probably be to include notebooks that are more or less complete tutorials (like the old one that was recently deleted: https://github.com/dsaxton/resample/blob/caa95e7b399b87752004dcffda3cd0e2a4e91c99/examples/resample.ipynb) rather short "in progress" ones. How about including the notebook from the scikit-hep presentation (or a variation thereof), which seemed pretty comprehensive?

**Comment by HDembinski** [comment]
> My preference would probably be to include notebooks that are more or less complete tutorials 

I think having something is better than having nothing. We can always improve these resources.

> (like the old one that was recently deleted: https://github.com/dsaxton/resample/blob/caa95e7b399b87752004dcffda3cd0e2a4e91c99/examples/resample.ipynb)

Good point, we should restore that as a notebook.

> How about including the notebook from the scikit-hep presentation (or a variation thereof), which seemed pretty comprehensive?

I was about to ask you about that, I think it makes sense to add. The talk is a bit long and detailed for a tutorial, but like I said, having something is better than having nothing at this point. We can replace these resources if we have better ones.

**Comment by dsaxton** [comment]
I guess we can merge them, although we should try to update soon with more helpful tutorials (FYI I renamed the folder to notesbooks, fixed a typo in the text, and did a clean rerun)

**Pull request merged**
