### PR TITLE
Update jackknife docstrings

### PR DESCRIPTION
**Pull request by dsaxton**
Small docstring edits for consistency / aesthetics

### CODE REVIEW

**Comment by HDembinski** [comment]
Shoot, I just wrote a similar patch before seeing this.

**Comment by HDembinski** [comment]
I merged your patch with mine.

**Comment by dsaxton** [comment]
@HDembinski Nice additions, will merge this in if no other comments

**Comment by HDembinski** [comment]
No other comments. I you want, I can also explicitly "approve" but I prefer to just comment when among friendly people.

**Comment by dsaxton** [comment]
> No other comments. I you want, I can also explicitly "approve" but I prefer to just "comment" in the review interface when among friendly people.

Just commenting is fine by me

**Pull request merged**
