### PR TITLE
Rename higher-order functions

### PR DESCRIPTION
**Pull request by dsaxton**
Closes https://github.com/dsaxton/resample/issues/31

While I don't think these names are great necessarily they're better than the `_fn` suffixes being used currently (I think `quantile_function_gen` is a slight improvement over `quantile_gen` since it makes it clear it's the quantile function that's being returned).

Also doing some other small cleaning (i.e., import sorting, removing what seem to be unnecessary underscore prefixes in imports; the functions aren't internal to the module and if they were I'd think the underscore should be part of the name). I'm actually surprised the CI wasn't failing due to formatting issues.

### CODE REVIEW

**Comment by HDembinski** [comment]
> I'm actually surprised the CI wasn't failing due to formatting issues.

What do you use to get the extra formatting and reordering of imports? It would be good if we use the same automatic tools.

**Comment by HDembinski** [comment]
> removing what seem to be unnecessary underscore prefixes in imports

I added the underscores originally in an attempt to hide these imports, but that does not work so it is fair to remove them.

My goal was/is to keep the namespace of the module clean, so that IDEs which support auto-completion only autocomplete on the actual content of the module, not on stuff the module itself imports to make things working. I have to do more research to find out how to do this properly. Perhaps by setting `__all__`

**Comment by dsaxton** [comment]
> My goal was/is to keep the namespace of the module clean, so that IDEs which support auto-completion only autocomplete on the actual content of the module, not on stuff the module itself imports to make things work. I have to do more research to find out how to do this properly. Perhaps by setting `__all__`

Ah, that makes sense

**Comment by dsaxton** [comment]
> What do you use to get the extra formatting and reordering of imports? It would be good if we use the same automatic tools.

I'm using isort: https://github.com/timothycrosley/isort. It does things like alphabetical ordering and ordering according to standard library / third-party / etc.

**Pull request merged**
